// The pool. `js/data/lots.js` is generated by `tools/bake.mjs` and is the only level data
// this game has: there is no hand-authored puzzle anywhere in the repo, because a puzzle is
// only worth shipping once a complete enumeration has said what it costs.
//
// This module reads that file and answers four questions:
//   * give me lot <id>              (share links, `#/lot/<id>`)
//   * give me the campaign order    (`#/c/<n>`, unlock-gated)
//   * give me today's puzzle        (`#/daily`, same lot for everyone, no server)
//   * give me a random one in band T (`#/random/<tier>`, re-rolls freely)
//
// It also re-verifies, at module load and in a *different* way than the bake did, that each
// row is what it claims to be: the row carries the route, and applying that route to the
// row's start board has to make the equation true. That check is cheap (a handful of moves),
// so it can run in the browser on boot; the expensive part — "no shorter route exists" — stays
// in solve.js and is re-run by `npm test` rather than by the page.

import { compileShape, decodeHex, legal, holds, planMove, showState, countLit } from './board.js';
import { LOTS } from '../data/lots.js';
import { hashSeed, rngFrom } from './rng.js';

let cache = null;

// Campaign order: measured par first, then the generator band, then the bake's own order.
// Nothing here guesses at difficulty — `par` is the enumeration's verdict, copied verbatim
// out of the baked file.
const TIER_ORDER = { single: 0, splay: 1, setup: 2, tangle: 3, deep: 4 };

// Apply a serialised route; throws on the first step the rules refuse. Kept separate from
// `verifyRow` so a test can ask for the end board and look at it.
export function followRoute(shape, state, route) {
  let cur = state;
  for (const m of route) {
    const plan = planMove(shape, cur, m.off, m.on);
    if (!plan) throw new Error(`route step ${m.off}→${m.on} is not a 搬`);
    if (legal(shape, plan.next)) throw new Error(`route step ${m.off}→${m.on} lands on an illegal board`);
    cur = plan.next;
  }
  return cur;
}

// The boot-time integrity check for one row: legal start, not already true, locked segments
// untouched, route length equals the printed par, and the route really solves it.
//
// It reports, it does not throw: `pool()` runs this over the whole file at boot, so a route
// naming a step that is not a 搬 at all has to come back as `{ ok: false, reason }` and land in
// `rejected()` — otherwise one corrupt row takes the page down instead of showing up as the
// broken row it is.
export function verifyRow(row) {
  const shape = compileShape(row.spec);
  const state = decodeHex(row.state);
  if (state.length !== shape.n) return { ok: false, reason: 'state length' };
  const err = legal(shape, state);
  if (err) return { ok: false, reason: `start illegal: ${err}` };
  if (holds(shape, state)) return { ok: false, reason: 'start is already true' };
  if (row.route.length !== row.par) {
    return { ok: false, reason: `route is ${row.route.length} 搬 but par says ${row.par}` };
  }
  let end;
  try {
    end = followRoute(shape, state, row.route);
  } catch (e) {
    return { ok: false, reason: String((e && e.message) || e) };
  }
  if (!holds(shape, end)) return { ok: false, reason: 'the printed route does not solve it' };
  if (countLit(end) !== countLit(state)) return { ok: false, reason: 'match count changed' };
  return { ok: true, shape, state, end };
}

function normalize(rows) {
  const lots = [];
  const bad = [];
  for (const row of rows) {
    const check = verifyRow(row);
    if (!check.ok) { bad.push(`${row.id}: ${check.reason}`); continue; }
    lots.push({
      id: row.id,
      tier: row.tier,
      spec: row.spec,
      par: row.par,
      proof: row.proof,
      n1: row.n1,
      n2: row.n2,
      states: row.states,
      space: row.space,
      pairs: row.pairs,
      ms: row.ms,
      text: row.text || showState(check.shape, check.state),
      answerText: showState(check.shape, check.end),
      lit: countLit(check.state),
      segments: check.shape.segCount,
      hex: row.state,
      state: check.state,
      route: row.route,
      shape: check.shape,
    });
  }
  return { lots, bad };
}

export function pool() {
  if (cache) return cache;
  cache = normalize(LOTS);
  return cache;
}

// Rows the shipped pool could not vouch for. Empty in a healthy build; the shell prints it
// rather than hiding it, because a silently dropped lot is exactly the kind of thing this
// repo is not supposed to do.
export function rejected() {
  return pool().bad;
}

export function allLots() {
  return pool().lots;
}

export function lotById(id) {
  return pool().lots.find((l) => l.id === id) || null;
}

export function lotIndex(id) {
  return pool().lots.findIndex((l) => l.id === id);
}

// The campaign order. Fixed by the baked file: measured par first, then the generator band,
// then the bake's own order (the index the row sits at in `js/data/lots.js`, which is the
// order the bands were filled in), so a re-bake from the same seed gives the same sequence.
export function campaign() {
  return allLots().slice().sort(
    (a, b) => (a.par - b.par)
      || ((TIER_ORDER[a.tier] ?? 9) - (TIER_ORDER[b.tier] ?? 9))
      || (lotIndex(a.id) - lotIndex(b.id)),
  );
}

// `n` is a 1-based ladder position — that is what `#/c/<n>` and the save file's `unlocked`
// counter carry — so it is clamped into [1, length] and *then* turned into an index. Reading
// it as an array index directly off-by-one'd the whole campaign: `campaignAt(1)` handed out
// the second-cheapest lot, and `campaignAt(campaignLength())` — the last rung, the one the
// "共 N 题" label points at — walked off the end and returned null.
export function campaignAt(n) {
  const list = campaign();
  if (!list.length) return null;
  const rung = Math.min(Math.max(1, n | 0), list.length);
  return list[rung - 1] || null;
}

export function campaignLength() {
  return campaign().length;
}

// Tier bands, with the difficulty claims computed *from the shipped rows* rather than from
// what the generator hoped for — if a band is empty in this build, `count: 0` says so.
export function tiers() {
  const meta = [
    { key: 'single', label: '单挑', blurb: '一步，而且只有一步' },
    { key: 'splay', label: '多解', blurb: '一步，但入口不止一个' },
    { key: 'setup', label: '布局', blurb: '两步：第一步是为第二步铺路' },
    { key: 'tangle', label: '缠绕', blurb: '三步，最短解唯一或近乎唯一' },
    { key: 'deep', label: '深水', blurb: '三步，且有多条最短解' },
  ];
  const lots = allLots();
  return meta.map((t) => {
    const mine = lots.filter((l) => l.tier === t.key);
    const pars = mine.map((l) => l.par);
    return {
      ...t,
      count: mine.length,
      par: mine.length ? Math.max(...pars) : null,
      parMin: mine.length ? Math.min(...pars) : null,
      space: mine.length ? Math.max(...mine.map((l) => l.space || 0)) : 0,
      states: mine.length ? Math.max(...mine.map((l) => l.states || 0)) : 0,
      ms: mine.length ? Math.max(...mine.map((l) => l.ms || 0)) : 0,
    };
  });
}

export function tierLabel(key) {
  const t = tiers().find((x) => x.key === key);
  return t ? t.label : key;
}

export function lotsInTier(key) {
  return allLots().filter((l) => l.tier === key);
}

export function dateKey(d = new Date()) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

// Today's puzzle: a hash of the date picks a lot, so two players on the same day get the same
// board with no server and no account. `day` is a parameter so the test can pin it.
export function dailyLot(day = dateKey()) {
  const lots = allLots();
  if (!lots.length) return null;
  return lots[hashSeed(`daily|${day}`) % lots.length];
}

// "Give me another one" without a server: the caller supplies a token (a fresh random string
// per press) and the same token always yields the same lot, so a re-roll is shareable.
export function randomLot(tierKey, token = String(Date.now())) {
  const mine = tierKey && tierKey !== 'any' ? lotsInTier(tierKey) : allLots();
  if (!mine.length) return null;
  const rng = rngFrom(`random|${tierKey}|${token}`);
  return rng.pick(mine);
}

// Numbers the about/panel views print, all recomputed from the rows that actually shipped.
export function stats() {
  const lots = allLots();
  const byPar = {};
  for (const l of lots) byPar[l.par] = (byPar[l.par] || 0) + 1;
  return {
    lots: lots.length,
    rejected: rejected().length,
    byPar,
    parMax: lots.length ? Math.max(...lots.map((l) => l.par)) : 0,
    spaceMax: lots.length ? Math.max(...lots.map((l) => l.space || 0)) : 0,
    statesMax: lots.length ? Math.max(...lots.map((l) => l.states || 0)) : 0,
    msMax: lots.length ? Math.max(...lots.map((l) => l.ms || 0)) : 0,
    proofs: [...new Set(lots.map((l) => l.proof))].sort(),
  };
}

// The one thing this repo promises, readable without running a search: every shipped lot's
// par came from a finished enumeration ('exhaustive-1' or 'exhaustive-bfs'). A starved sweep
// prints no proof label at all, so if a row ever shows up with anything else here, this stops
// the page rather than quietly showing an unverified number.
export function auditProofs() {
  return allLots().filter((l) => l.proof !== 'exhaustive-1' && l.proof !== 'exhaustive-bfs')
    .map((l) => `${l.id} proof=${l.proof}`);
}
